### ISSUE TITLE
dhis2 2.30 problem

### ISSUE THREAD

**Issue by linxd** [hisptz/hisptz-touch#66]
when login into dhis2 2.30 server, got:
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.hisp.dhis.user.UserCredentials.userAuthorityGroups,could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwL............

**Comment by chingalo** [comment]
Hello Linxd,
Are using master branch or stable-mobile-dev or from [google play store](https://play.google.com/store/apps/details?id=com.hipstz.dhis2.dhis2touch)

**Comment by linxd** [comment]
get from github master, build. and install.


for play.dhis2.org/2.29, can login into , but can't open dashboard app 's map view.
for my dhis 2.29 server ,can't login, status:409 ,http status,conflict, error code :409,   error ,property path: path
==================
for  play.dhis2.org/2.30, say ... ailed to lazily initialize a collection of role...
catalina.out:
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.hisp.dhis.user.UserCredentials.userAuthorityGroups, could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:582)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:201)
        at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:561)




--

此致

easy

莫愁前路无知己，天下谁人不识君。

At 2018-10-11 22:53:56, "Joseph Chingalo" <notifications@github.com> wrote:


Hello Linxd,
Are using master branch or stable-mobile-dev or from google play store
