### ISSUE TITLE
error httpstatus code :409,  status:"error",path property : path

### ISSUE THREAD

**Issue by linxd** [hisptz/hisptz-touch#69]
when login to my dhis2 2.29 server, got this error

**Comment by linxd** [comment]
but can login to play.dhis2.org/2.29

**Comment by linxd** [comment]
to 2.30: got error  500:  failed to lazily initialize  a collection of role :org.hisp.dhis.user.UserCredentials .userAuthorityGroups, could not initialize  proxy- no session

**Comment by chingalo** [comment]
Hello Linxd, 
Are using master branch or stable-mobile-dev or from  [google play store](https://play.google.com/store/apps/details?id=com.hipstz.dhis2.dhis2touch)

**Comment by linxd** [comment]
master branch

**Comment by linxd** [comment]
yesterday master branch some times can login to 2.30.

**Comment by linxd** [comment]
the master code now, got log:

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.hisp.dhis.user.UserCredentials.userAuthorityGroupe proxy - no Session
        at rg.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:582
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:201)
        at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:561)
        at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
        at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)

**Comment by linxd** [comment]
yesterday code can login, but when open dashboard got error:
 aw,snap, we are sorry for this inconvenience ,our server tell us that error-(error code 500)

error, httpstatuscode 500,... failed to lazily initialize a collection of role: org.hisp.dhis.user.UserCredentials.userAuthorityGroups,could not initilze proxt- no session...

**Comment by linxd** [comment]
also: can't clean local metadata of program.(when choose the program, the operation will fail)

**Comment by linxd** [comment]
the newest code can login to play.dhis2,org/2.29, but can't to 2.30, 
for my server, 2.29 or 2.30 all can't. (my 2.29 has updated to the newest github source code)

**Comment by linxd** [comment]
the android version problem? my android 7.1.1

**Comment by linxd** [comment]
for 2.29, no error log in catalina.out
for 2.30: 
* WARN  2018-10-13 13:59:00,064 Authentication event AuthenticationSuccessEvent: admin; details: org.springframework.security.web.
authentication.WebAuthenticationDetails@59b2: RemoteIpAddress: 118.113.211.136; SessionId: null (LoggerListener.java [http-nio-8080-exec-70])
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.hisp.dhis.user.UserCredentials.userAuthorityGroups, could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:582)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:201)
        at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:561)
        at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
        at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)
        at org.hisp.dhis.user.UserCredentials.getAllAuthorities(UserCredentials.java:204)
        at org.hisp.dhis.user.UserCredentials.getAuthorities(UserCredentials.java:782)
        at org.hisp.dhis.user.DefaultCurrentUserService.getCurrentUserInfo(DefaultCurrentUserService.java:117)
        at sun.reflect.GeneratedMethodAccessor445.invoke(Unknown Source)




--

此致

   林晓东

莫愁前路无知己，天下谁人不识君。

在 2018-10-11 22:57:02，"Joseph Chingalo" <notifications@github.com> 写道：


Have you checked tomcat logs while the app tries to login into you instance?
But we usually return error response from server

**Comment by linxd** [comment]
??
